#!/usr/bin/env php
<?php

use Toolkit\Cli\App;

define('BASE_PATH', dirname(__DIR__));

require dirname(__DIR__) . '/test/boot.php';

// create app instance
$app = new App([
    'desc' => 'this is my cli application',
]);

// register commands

// use closure
$app->addCommand('test', function ($app) {
    echo "args:\n";
    /** @var Toolkit\Cli\App $app */
    /** @noinspection ForgottenDebugOutputInspection */
    print_r($app->getArgs());

}, [
  'desc' => 'the description text for the command: test',
]);

// Use an object
$app->addObject(new class
{
    public function getHelpConfig(): array
    {
        $help = <<<STR
Options:
  --info    Output some information

Example:
  {{command}}

STR;

        return [
            'name'  => 'list',
            'desc'  => 'list all swoft components in src/ dir',
            'help'  => $help,
        ];
    }

    public function __invoke(App $app)
    {
        echo "hello\n";
    }
});

// run
$app->run();
