name: Unit-tests

on:
  push:
    paths:
      - '**.php'
      - 'composer.json'
      - '**.yml'

jobs:
  test:
    name: Test on php ${{ matrix.php}} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        php: [7.3, 7.4, 8.0]
        os: [ubuntu-latest, macOS-latest] # windows-latest,
        include:
          - os: 'ubuntu-latest'
            php: '7.2'
            phpunit: '8.5.13'
          - os: 'ubuntu-latest'
            php: '7.1'
            phpunit: '7.5.20'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # usage refer https://github.com/shivammathur/setup-php
      - name: Setup PHP
        timeout-minutes: 5
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php}}
          tools: pecl, php-cs-fixer, phpunit:${{ matrix.phpunit }}
          extensions: mbstring, dom, fileinfo, mysql, openssl, igbinary, redis # , swoole-4.4.19 #optional, setup extensions
          ini-values: post_max_size=56M, short_open_tag=On #optional, setup php.ini configuration
          coverage: none #optional, setup coverage driver: xdebug, none

      - name: Display Env
        run: env

      - name: Install dependencies
        run: composer install --no-progress

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Run unit tests
#        run: composer run test
        run: phpunit -vv
